alias ls='ls --color=auto'
alias ll='ls -l'
eval $(dircolors -b /etc/dircolors)

# Setup a red prompt for root and a green one for users. 
NORMAL="\[\e[0m\]"
RED="\[\e[1;31m\]"
GREEN="\[\e[1;32m\]"
if [[ $EUID == 0 ]] ; then
	PS1="$RED\u [ $NORMAL\w$RED ]# $NORMAL"
else
	PS1="$GREEN\u [ $NORMAL\w$GREEN ]\$ $NORMAL"
fi

if [ "`locale charmap 2>/dev/null`" = "UTF-8" ]
then
	stty iutf8
fi
