#!/bin/sh
NAME="$1"
VERS="$2"
if [ ! -f $NAME-$VERS.tar.gz ] ; then
echo "Attempting to fetch $NAME-$VERS.tar.gz from ftp.gnu.org via ftp..."
ftp -n << END
open ftp.gnu.org
user anonymous
passive
binary
cd gnu/$NAME
get $NAME-$VERS.tar.gz
bye
END
fi
